packages:
  - apps/*
  - packages/*
  - tools/*
  - docs

allowBuilds:
  "0": "@parcel/watcher"
  "1": better-sqlite3
  "2": esbuild
  "3": sharp
  "4": vue-demi

catalog:
  "@types/node": ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7

catalogMode: prefer
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
