packages:
  - apps/*
  - packages/*
  - tools/*
  - docs

allowBuilds:
  "0": "@parcel/watcher"
  "1": better-sqlite3
  "2": esbuild
  "3": sharp
  "4": vue-demi

catalog:
  "@types/node": ^24
  "@vitest/browser-playwright": 4.1.7
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.22
  vite-plus: ^0.1.22
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.22

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
